name: SSH Runner Access

on:
  workflow_dispatch:

jobs:
  ssh-session:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start SSH Session (tmate)
        uses: mxschmitt/action-tmate@v3
        with:
          detached: false
          connect-timeout-seconds: 30
